### ISSUE TITLE
how to use this library.

### ISSUE THREAD

**Issue by shamaru001** [Aloxord/createElementsLib#1]
a example please.

**Comment by Aloxord** [comment]
hi buddy, this library is under develop yet, but i can show how to use at this time:
 if you want to do a "div" element with a "example" class and id, you can do that:

```
k("div",{
    class: "example",
    id:"example"
})
or
k("div#example.example")
```
and to put into this element another element:

```
k("div",{
    class:"myFirst",
},[ 
   k("div",{
    class: "mysecond",
    })
])
```

**Comment by Aloxord** [comment]
we are uploading a readme file soon with the final build :) thanks for visit

**Comment by shamaru001** [comment]
I understood,  thanks for your answers and explanation.
